### ISSUE TITLE
DATAQUALITY-1.0.2-SNAPSHOT.omod stopping NMRS Landing Page

### ISSUE THREAD

**Issue by abrahamolatubosun1973** [nmrs-nigeria/files_and_resources#7]
Hi IHVN team,

We deployed this module into our testing instance of NMRS at first it shows up and we were able to validate some patient records and fixed some. We intend to continue the validation process the next day starting the NMRS became another issue because we couldn't successfully get to the landing page due to the 

long processing of previous validation.

please find attached the sample of processing.

thank you

![NMRS_START_20-05-2021](https://user-images.githubusercontent.com/14082777/119008064-bb5ca080-b989-11eb-87db-640e5cdd22be.png)

**Comment by gibrilg** [comment]
Thank you, Abraham, i believe this issue was resolved? I will proceed and closed the thread. Please feel free to reopen it if it's still pending.
