### ISSUE TITLE
Care/ART Cards failed to save due to EDD in the future.

### ISSUE THREAD

**Issue by akoruji** [nmrs-nigeria/files_and_resources#9]
After the upgrade, care card failed to save when pregnancy data is entered such as LMP, GA and EDD. The error message is: Cannot be in the future. The implication of this is that care cards won’t save for pregnant women on care.
Thanks and well done.

![Capture](https://user-images.githubusercontent.com/39161333/130646373-85fdd5f6-86a3-487e-9221-9968c300aee0.PNG)

**Comment by gibrilg** [comment]
Thank you Akoruji for this comment. This issue is resolved and closed.
